activities:
  - humanName: Reference Image
    id: image-custom
    projectType: Tutorial
    source:
      data: Custom
      type: Custom
  - description: Workbook.
    humanName: Dunn
    id: dunn
    projectType: Tutorial
    source:
      data: Dunn
      type: Freeform
  - description: Dissections exercise
    humanName: Dissections
    id: fundamentals_2_dissections
    projectType: Tutorial
    source:
      data:
        categories:
          - textures/pinterest
        files:
          - female_clothed/test/rina1.png
        imageCount: 10
      type: Categories
  - humanName: Free Draw
    id: free_draw
    projectType: Free
    source:
      data: Free draw.
      type: Freeform
presetOrder:
  free:
    - fig_dab2_3
    - test
  tutorial:
    - fig_dab2_3
    - test
presets:
  - humanName: Figures/DaB 2.3 Dissections
    id: fig_dab2_3
    regimens:
      - categories:
          - female_clothed
        regimenId: figure_30
      - regimenId: textures
  - humanName: Test
    id: test
    regimens:
      - regimenId: textures
regimens:
  - activities:
      - activityId: image-custom
        durationMinutes: 1
        unboundedDuration: false
      - activityId: image-custom
        durationMinutes: 1
        unboundedDuration: false
      - activityId: image-custom
        durationMinutes: 1
        unboundedDuration: false
      - activityId: image-custom
        durationMinutes: 1
        unboundedDuration: false
      - activityId: image-custom
        durationMinutes: 1
        unboundedDuration: false
      - activityId: image-custom
        durationMinutes: 1
        unboundedDuration: false
      - activityId: image-custom
        durationMinutes: 2
        unboundedDuration: false
      - activityId: image-custom
        durationMinutes: 2
        unboundedDuration: false
      - activityId: image-custom
        durationMinutes: 5
        unboundedDuration: false
      - activityId: image-custom
        durationMinutes: 5
        unboundedDuration: false
      - activityId: image-custom
        durationMinutes: 10
        unboundedDuration: false
    defaultCategories: []
    humanName: "Figure drawing (30 minutes, 1-1-1-1-1-1-2-2-5-5-10)"
    id: figure_30
  - activities:
      - activityId: fundamentals_2_dissections
        durationMinutes: 1
        unboundedDuration: true
    defaultCategories: []
    humanName: Textures
    id: textures
